title: <a href="https://shashankbarthwal.com/">Shashank Barthwal</a>
description: Security Researcher and a passionate Programmer<br><a href="/"><button>Home</button></a><a href="/walkthroughs/"><button>Walkthroughs</button></a><a href="/articles/"><button>Articles</button></a>
theme: jekyll-theme-slate
